from PyQt5 import QtCore, QtGui, QtWidgets

class Settings_Ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 546)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(13)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\project\\CIConfig\\res\\used_icons/设置.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l_icon_pathToCI = QtWidgets.QLabel(self.centralwidget)
        self.l_icon_pathToCI.setGeometry(QtCore.QRect(40, 60, 41, 41))
        self.l_icon_pathToCI.setText("")
        self.l_icon_pathToCI.setPixmap(QtGui.QPixmap("d:\\project\\CIConfig\\res\\used_icons/文件路径.png"))
        self.l_icon_pathToCI.setScaledContents(True)
        self.l_icon_pathToCI.setObjectName("l_icon_pathToCI")
        self.l_title = QtWidgets.QLabel(self.centralwidget)
        self.l_title.setGeometry(QtCore.QRect(20, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(14)
        self.l_title.setFont(font)
        self.l_title.setObjectName("l_title")
        self.l_pathToCI_info = QtWidgets.QLabel(self.centralwidget)
        self.l_pathToCI_info.setGeometry(QtCore.QRect(90, 60, 281, 41))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(13)
        self.l_pathToCI_info.setFont(font)
        self.l_pathToCI_info.setObjectName("l_pathToCI_info")
        self.l_pathToCI = QtWidgets.QLabel(self.centralwidget)
        self.l_pathToCI.setGeometry(QtCore.QRect(90, 103, 551, 31))
        self.l_pathToCI.setText("")
        self.l_pathToCI.setObjectName("l_pathToCI")
        self.b_pathToCI = QtWidgets.QPushButton(self.centralwidget)
        self.b_pathToCI.setGeometry(QtCore.QRect(380, 59, 101, 41))
        self.b_pathToCI.setObjectName("b_pathToCI")
        self.l_MainWindow = QtWidgets.QLabel(self.centralwidget)
        self.l_MainWindow.setGeometry(QtCore.QRect(40, 158, 38, 38))
        self.l_MainWindow.setText("")
        self.l_MainWindow.setPixmap(QtGui.QPixmap("d:\\project\\CIConfig\\res\\used_icons/主界面.png"))
        self.l_MainWindow.setScaledContents(True)
        self.l_MainWindow.setObjectName("l_MainWindow")
        self.l_pathToCI_info_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_pathToCI_info_2.setGeometry(QtCore.QRect(90, 158, 281, 41))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(13)
        self.l_pathToCI_info_2.setFont(font)
        self.l_pathToCI_info_2.setObjectName("l_pathToCI_info_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 160, 71, 36))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(90, 136, 471, 20))
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CIConfig - 设置"))
        self.l_title.setText(_translate("MainWindow", "设置选项"))
        self.l_pathToCI_info.setText(_translate("MainWindow", "ClassIsland可执行文件路径:"))
        self.b_pathToCI.setText(_translate("MainWindow", "修改"))
        self.l_pathToCI_info_2.setText(_translate("MainWindow", "启动时显示主界面:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "  否"))
        self.comboBox.setItemText(1, _translate("MainWindow", "  是"))